version: '3.8'
services:
  db:
    image: postgres
    container_name: finance_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: finance_db
    ports:
      - '5432:5432'
