services:
  - type: web
    name: finance-tracker-api
    env: node
    region: oregon
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    buildCommand: |
      corepack enable
      pnpm install --frozen-lockfile
      pnpm build
    startCommand: node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Render sets PORT; respect it in Nest (see note below)
      - key: JWT_SECRET
        sync: false # set in dashboard after first deploy
      - key: CORS_ORIGIN
        sync: false # set in dashboard after first deploy
      - key: DATABASE_URL
        fromDatabase:
          name: finance-tracker-db
          property: connectionString

databases:
  - name: finance-tracker-db
    plan: free
