services:
  - type: web
    name: finance-tracker-api
    env: node
    region: oregon
    plan: free
    autoDeploy: true
    buildCommand: |
      corepack enable
      if [-f pnpm-lock.yaml]; then
        pnpm install --frozen-lockfile
      else
        pnpm install --no-frozen-lockfile
      fi
      pnpm build
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Render sets PORT; respect it in Nest (see note below)
      - key: JWT_SECRET
        sync: false # set in dashboard after first deploy
      - key: CORS_ORIGIN
        sync: false # set in dashboard after first deploy
      - key: DATABASE_URL
        fromDatabase:
          name: finance-tracker-db
          property: connectionString
    startCommand: pnpm start:prod
    healthCheckPath: /health

databases:
  - name: finance-tracker-db
    plan: free
