services:
  - type: web
  name: finance-tracker-api
  env: node
  region: oregon
  plan: free
  buildCommand: |
    corepack enable
    pnpm install --frozen-lockfile
    pnpm build 
  envVars:
  - key: NODE_ENV
    value: production
  - key: PORT 
    value: 10000
  - key: JWT_SECRET
    sync: false 
  - key: CORS_ORIGIN
    sync: false
  - key: DATABASE_URL
    fromDatabase: 
      name: finance-tracker-db
      property: connectionString
  autoDeploy: true
  healthCheckPath: /health
  plan: free 
  startCommand: pnpm start:prod
databases:
  - name: finance-tracker-db
  plan: free
